title:              Lazar Gugleta Blog
email:              lazar.gugleta@gmail.com
description:        Blog by Lazar Gugleta
author:             Lazar Gugleta
baseurl:            ""
url:                "https://lazargugleta.github.io"

# Social Profiles
twitter_username:   LazarGugleta
github_username:    lazargugleta
facebook_username:  lazar.gugleta
instagram_username:  lazar_gugleta
linkedin_username:  lazargugleta

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-123154622-2 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
